zookeeper:
  image: registry.banno-internal.com/zookeeper:latest

haproxy:
  image: registry.banno-internal.com/haproxy-sidecar:latest
  ports:
    - "80:80"
  links:
    - zookeeper

mesosmaster:
  image: registry.banno-internal.com/mesos-master:latest
  hostname: mesosmaster.dev.banno.com
  environment:
    MESOS_ZK: zk://zookeeper:2181/mesos
    MESOS_WORK_DIR: /mesos
    MESOS_QUORUM: 1
    MESOS_CLUSTER: dev.banno.com
  ports:
      - "5050:5050"
  links:
    - zookeeper

mesosagent:
  image: registry.banno-internal.com/mesos-slave:latest
  ports:
    - "5151:5151"
  hostname: mesosslave.dev.banno.com
  environment:
    MESOS_CONTAINERIZERS: docker,mesos
    MESOS_DOCKER_STOP_TIMEOUT: 30secs
    MESOS_LOG_DIR: /var/log
    MESOS_MASTER: zk://zookeeper:2181/mesos
    MESOS_WORK_DIR: /mesos
    MESOS_PORT: "5151"
    MESOS_HOSTNAME: mesosslave1.dev.banno.com
  volumes:
    - /sys:/sys
    - /var/run/docker.sock:/var/run/docker.sock
  links:
    - mesosmaster
    - zookeeper

marathon:
  image: mesosphere/marathon:v0.15.2
  ports:
    - "8080:8080"
  command: --master zk://zookeeper:2181/mesos --zk zk://zookeeper:2181/marathon
  links:
    - zookeeper
    - mesosmaster
    - mesosagent

# chronos:
#     image: chronos:latest
#     ports:
#       - "8081:8081"
#     command: --master zk://zookeeper:2181/mesos --zk_hosts zookeeper:2181 --http_port 8081
#     links:
#       - mesosmaster
#       - mesosagent
#       - marathon
#       - zookeeper
#       - haproxy
