zookeeper:
  image: registry.banno-internal.com/zookeeper:latest

haproxy:
  image: registry.banno-internal.com/haproxy-sidecar:latest
  ports:
    - "80:80"
  links:
    - zookeeper

mesosmaster:
  image: registry.banno-internal.com/mesos-master:latest
  hostname: mesosmaster.dev.banno.com
  environment:
    MESOS_ZK: zk://zookeeper:2181/mesos
    MESOS_WORK_DIR: /mesos
    MESOS_QUORUM: 1
    MESOS_CLUSTER: dev.banno.com
  ports:
      - "5050:5050"
  links:
    - zookeeper

mesosagent:
  image: registry.banno-internal.com/mesos-slave:latest
  ports:
    - "5151:5151"
  hostname: mesosslave.dev.banno.com
  environment:
    MESOS_CONTAINERIZERS: docker,mesos
    MESOS_DOCKER_STOP_TIMEOUT: 30secs
    MESOS_LOG_DIR: /var/log
    MESOS_MASTER: zk://zookeeper:2181/mesos
    MESOS_WORK_DIR: /mesos
    MESOS_PORT: "5151"
    MESOS_HOSTNAME: mesosslave1.dev.banno.com
  volumes:
    - /sys:/sys
    - /var/run/docker.sock:/var/run/docker.sock
  links:
    - mesosmaster
    - zookeeper

chronos:
  image: registry.banno-internal.com/chronos:latest
  environment:
    CHRONOS_HTTP_PORT: 8081
    CHRONOS_MASTER: zk://zookeeper:2181/mesos
    CHRONOS_ZK_HOSTS: zookeeper:2181
  ports:
    - "8081:8081"
  links:
    - mesosmaster
    - mesosagent
    - zookeeper

test:
  build: ./test
  links:
    - chronos
