image = "registry.banno-internal.com/chronos"
version = "2.4.0"

desc "Cleanup"
task :clean do
  sh "docker-compose kill"
  sh "docker-compose rm --all --force"
end

desc "Build the image"
task :build do
  sh "docker build -t #{image}:#{version} ."
  sh "docker tag #{image}:#{version} #{image}:latest"
end

desc "Build test image and run rspec tests"
task :test => :clean do
  sh "docker-compose up --build test"
end

desc "Push the build docker image"
task :push do
  sh "docker push #{image}:#{version}"
  sh "docker push #{image}:latest"
end
